# Generated by Django 5.0.4 on 2024-04-17 21:44

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DisplayAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="ads/"),
                ),
                ("headline", models.CharField(max_length=200)),
                ("body", ckeditor.fields.RichTextField()),
                ("cta_button_text", models.CharField(max_length=50)),
                ("cta_button_link", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=200)),
                (
                    "subheadline",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="offers/thumbnails/"
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("body", ckeditor.fields.RichTextField()),
                ("custom_code", models.TextField(blank=True, null=True)),
                (
                    "cta_button_text",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cta_button_link", models.URLField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=200)),
                (
                    "subheadline",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("body", ckeditor.fields.RichTextField()),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "youtube_video_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True, related_name="blogs", to="blog.category"
                    ),
                ),
                (
                    "selected_ads",
                    models.ManyToManyField(blank=True, to="blog.displayad"),
                ),
            ],
        ),
    ]
