# Generated by Django 5.0.4 on 2024-04-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blog_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displayad",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="static/ads/"),
        ),
    ]
