# Generated by Django 5.0.4 on 2024-04-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "testimonial_first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "testimonial_last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "testimonial_title",
                    models.CharField(max_length=200, verbose_name="Testimonial Title"),
                ),
                ("testimonial_body", models.TextField(verbose_name="Testimonial Body")),
            ],
        ),
    ]
