# Generated by Django 5.0.4 on 2024-04-17 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="user",
        ),
    ]
